/**
 * Compiles `mobile/native/*.swift` into the **main app target**.
 *
 * App Intents have to be in the app target, not in a pod or an extension:
 *
 *  * Xcode's App Intents metadata processor runs per target and scans that
 *    target's own Swift. Intents in a CocoaPods static library -- which is what
 *    an Expo local module compiles to -- are not picked up without an
 *    `AppIntentsPackage` re-export.
 *  * An extension would need its own App ID, and anything shared with it needs
 *    an App Group. Both are exactly what a free Apple account cannot provision.
 *
 * In the app target they need no entitlement at all, which is the point.
 *
 * `ios/` is regenerated by every prebuild, so the sources live outside it and
 * are copied in here.
 */

const { IOSConfig, withDangerousMod, withXcodeProject } = require("expo/config-plugins");
const fs = require("fs");
const path = require("path");

/** Where the Swift lives in the repo, relative to the Expo project root. */
const SOURCE_DIR = "native";
/** Subfolder inside the app target's group. */
const DEST_GROUP = "Native";

function swiftFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith(".swift"))
    .sort();
}

module.exports = function withAppIntents(config) {
  config = withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const { projectRoot, platformProjectRoot } = cfg.modRequest;
      const projectName = IOSConfig.XcodeUtils.getProjectName(projectRoot);
      const source = path.join(projectRoot, SOURCE_DIR);
      const destination = path.join(platformProjectRoot, projectName, DEST_GROUP);

      const files = swiftFiles(source);
      if (files.length === 0) {
        throw new Error(`[withAppIntents] no .swift files in ${source}`);
      }

      fs.rmSync(destination, { recursive: true, force: true });
      fs.mkdirSync(destination, { recursive: true });
      for (const name of files) {
        fs.copyFileSync(path.join(source, name), path.join(destination, name));
      }
      return cfg;
    },
  ]);

  config = withXcodeProject(config, (cfg) => {
    const { projectRoot } = cfg.modRequest;
    const projectName = IOSConfig.XcodeUtils.getProjectName(projectRoot);

    for (const name of swiftFiles(path.join(projectRoot, SOURCE_DIR))) {
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath: `${projectName}/${DEST_GROUP}/${name}`,
        groupName: `${projectName}/${DEST_GROUP}`,
        project: cfg.modResults,
      });
    }
    return cfg;
  });

  return config;
};
